# Generated by Django 6.0.2 on 2026-02-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_tag_recipe_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='serves',
        ),
    ]
