# Generated by Django 6.0.4 on 2026-04-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_serves'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='estimated_unit_cost_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
